### ISSUE TITLE
cannot install newest ccy with pytz 2023.03

### ISSUE THREAD

**Issue by mjamroz** [quantmind/ccy#28]
Is there any reason or wrong config of poetry? 
I can have either newest pytz and older ccy or opposite.

**Comment by lsbardel** [comment]
Not sure, I published a [new release with updated dependencies](https://github.com/quantmind/ccy/releases/tag/v1.3.1), that should fix your problem, let me know.
Btw, `pytz` will be removed in 1.4 (already in master), so this shouldn't be an issue anymore once that is out

**Comment by mjamroz** [comment]
it works, thank you!
